### ISSUE TITLE
RFE & Bug Android

### ISSUE THREAD

**Issue by rgleason** [seandepagnier/watchdog_pi#130]
Reported  by [nocheinpeter](https://github.com/nocheinpeter)
https://github.com/OpenCPN/plugins/issues/960
 Android: Watchdog PI geometry and functions #960 

On Android 11 (Samsung Galaxy Tab A) the watchdog pi v2.4.61.0 has following problems:

1.     settings tab plugins: setting for wd pi open "about" window, which cannot be closed; OpenCPN app then must be killed
2.     icon at menu bar is only a black rectangle
3.     wd pi window opened via menu bar hides menu bar's hamburger icon: changing geometry setting in opencpn.conf file (Settings/Watchdog: DialogPosX=100, ..Y=20) fixes the improber position
4.     wd pi window is to small (Settings/Watchdog: DialogWidth=500, ..Height=300) fixes small window
5.     wd window is missing alarms for depth, landfall, boundary, rudder, pypilot; notably depth alarm will be very helpful
6.     context menu on alarms is missing (e.g. to edit an alarm)

**Comment by rgleason** [comment]
1.     Preferences Tab "About Author" goes to a web page https://seandepagnier.users.sourceforge.net/
       On windows it works properly. On android the screen gets frozen and you have to close all apps and restart.
      Don't use About Author for now.

2.     Icon at menubar is black. On windows the icon shows properly, don't know what the problem is with Android at this point.
     Yes, I notice this too. Maybe Android does not support svg? or perhaps we did not include svg properly for android?
 
3.    Agreed, for android the opening menu obscures the Hamburger in the Toolbar, it should be offset.

4.    Agreed. Also the window is very very hard to drag open. wd pi window is to small (Settings/Watchdog: DialogWidth=500, ..Height=300) fixes small window

5. Agreed wd window is missing alarms for depth, landfall, boundary, rudder, pypilot; notably depth alarm will be very helpful.
  Only Anchor, Course, Speed, Wind, Weather, Deadman, Nmea Data are available. Why?

6    Agreed. Fixed. context menu on alarms is missing (e.g. to edit an alarm)

7. Also new users are unlikely to understand this interface, although it is very clever.
 I think we need a message showing when there are no Alarms in the menu!!!

**Comment by rgleason** [comment]
@nocheinpeter   Can you please test the current version of Watchdog on Android after updating the PIM catalog and installing and enabling Watchdog 2.4.103

**Comment by nocheinpeter** [comment]
Sam issues with that version. Even Item 6 - the context menu appears but editing of an alarm is disabled.

**Comment by rgleason** [comment]
@nocheinpeter Can you please test the current version of Watchdog 2.4.105  on Android after updating the PIM catalog and installing and enabling   Thanks.  We hope some of it is fixed. Please advise.

**Comment by nocheinpeter** [comment]
> @nocheinpeter Can you please test the current version of Watchdog 2.4.105 on Android after updating the PIM catalog and installing and enabling Thanks. We hope some of it is fixed. Please advise.

1. Settings -> Plugins -> Watchdog: Button "Website" there happens nothing. Button "Setting" open info dialog, but i cannot be closed with "OK". "About Author" has no action.

2. Icon at menubar is still black.

3.  Plugin window has now offset.

4. Plugin window cannot be resized or moved.

5. Alarms for depth, landfall, boundary, rudder, pypilot are still missing.

6. Context menu on alarms does not work. At my Motoral G41 it works but not on my Samsung Galaxy Tab A 2019.
